### ISSUE TITLE
COLOCAR  EN CUADRICULA LA IMAGEN REFERENTE AL PRODUCTO./ PLACE THE IMAGE OF THE PRODUCT IN THE GRID

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#104]
### EXPLANATION

En la vista de proveedores se deben colocar en cada una de las cuadriculas que aparecen allí la imagen referente  a cada producto.

In the suppliers view, the image of each product must be placed in each of the grids that appear there.

### SCREENSHOTS:

![Image](https://user-images.githubusercontent.com/111365000/186190140-dd5c7bf2-7c09-4639-b2b5-4ed91aa1b6b8.png)

![Image](https://user-images.githubusercontent.com/111365000/186190481-b98fda49-9afa-4002-afb1-c5eb9f1973b2.png)

### USER STORY

Yo como usuario quiero que al entrar a la vista de proveedores pueda encontrar la imagen de cada uno de los productos ofrecidos en esa parte.

As a user I want that when entering the list of suppliers I can find the image of each of the products offered in that part.

### ACEPTANCE CRITERIA

En la vista de proveedores aparecerán la imagen de cada uno de los productos ofrecidos.

In the suppliers view, the image of each of the products offered will appear.

### REFERENCE

https://www.google.com/search?q=imagenes+para+logo+dereferencia+de+monta%C3%B1as+y+paisaje&tbm=isch&ved=2ahUKEwio9siJ-OL5AhVoqIQIHRd3AM4Q2-cCegQIABAA&oq=imagenes+para+logo+dereferencia+de+monta%C3%B1as+y+paisaje&gs_lcp=CgNpbWcQAzoECCMQJ1CqC1jDK2D-L2gAcAB4AIABpwGIAY4MkgEEMC4xMZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=7ekHY-jLFujQkvQPl-6B8Aw

**Comment by Eghinner** [comment]
@mdrianislam0or1 Im sorry, this was solve for https://github.com/Azordev/did-admin-panel/issues/105
