### ISSUE TITLE
AÑADIR LA OPCIÓN "PROVEEDOR"/ ADD THE SUPPLIER OPTION.

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#108]
### EXPLANATION.
Al seleccionar la opción "Proveedores", se habré una vista de pantalla donde se encontrara una lista de proveedores,también se encontrara  la opción " añadir nuevo proveedor" este botón sera exclusivo para proveedores interesados.Esta opción estará en la parte superior de la pantalla tendrá como función  de dar paso a una vista de pantalla que pedirá los datos del nuevo proveedor

By selecting the "Suppliers" option, you will open a screen view where you will find a list of suppliers, you will also find the option "add new supplier" this button will be exclusive for interested suppliers, this option will be at the top of the screen and will have the function of giving way to a screen view that will ask for the new supplier's data.
You will find the option "add supplier" this button will be exclusive for interested suppliers.

### SCREESHOTS

![image](https://user-images.githubusercontent.com/4030477/187299052-594ae3b5-2f77-4058-bdcf-576bcf1766d6.png)

![Image](https://user-images.githubusercontent.com/111365000/186040396-a4412b35-8341-47f6-8b7d-7d0ca5cf2d1e.png)

### USER STORY:

Yo como usuario quiero que en la vista de proveedores haya la opción de "añadir nuevo proveedor" para que los interesados puedan hacer parte de DID.

As a user, I would like to have the option to "add new supplier" in the suppliers view so that interested parties can become part of DID.

### ACCEPTANCE CRITERIA:

Se dará la opción "añadir nuevo proveedor", en la parte superior de la pantalla.

The option "add new supplier" will be given at the top of the screen.

### USE CASES:

En el botón + reaccionara el cursor para darle clic y añadir al nuevo proveedor.

In the + button the cursor will react to click and add the new supplier.

**Comment by gabrielrevelo** [comment]
A que se refieren con esto?:

When programming add state on active or inactive button in red
