### ISSUE TITLE
HABILITAR VISTA DE AÑADIR SOCIOS PARA CONSTATAR INFORMACION./ ENABLE ADD PARTNERS VIEW TO CHECK INFORMATION.

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#115]
PROJECT TASK TEMPLATE.

### EXPLANATION

Después de haber seleccionado  el botón  añadir  se desplegara una vista donde podremos observar  la información  del nuevo socio en una barra horizontal, donde encontramos el código, fecha, socio, correo electrónico ,contraseña, estado (mostrando en un ovalo con un color verde indicando que esta activo)  y al final un botón con una imagen que daría a entender que se puede editar.

After selecting the add button a view will be displayed where we can see the information of the new member in a horizontal bar, where we find the code, date, member, email, password, state ( showing in an oval with a green color indicating that it is active) and at the end a button with an image that would indicate that it can be edited.

### SCREENSHOTS

![Image](https://user-images.githubusercontent.com/111365000/186708380-3c3e4d69-7c77-4c36-8889-84bcfa0ebfb9.png)

### CHECKLIST

Al seleccionar el botón añadir, debe aparecer una vista donde esté la información del socio previamente añadida, ademas tiene que haber un ovalo e indique con color verde que esta activo y a su lado derecho un botón que indica editar.

When selecting the add button, a view should appear with the member's information previously added, there should also be an oval and indicate with green color that it is active and on the right side a button that indicates edit.

### REFERENCES

![Image](https://user-images.githubusercontent.com/111365000/186710234-cafc49e3-282c-45ba-a940-e6801fc03353.png)

SUGGESTED DESIGN:
https://www.google.com/search?q=boton+editar&tbm=isch&ved=2ahUKEwjP5oGVq-L5AhWjwikDHUd2AyYQ2-cCegQIABAA&oq=boton+editar&gs_lcp=CgNpb

**Comment by Eghinner** [comment]
Similar to https://github.com/Azordev/did-admin-panel/issues/125

**Comment by JRS-Developer** [comment]
How can I get the Edit icon from the design?

**Comment by Eghinner** [comment]
https://www.svgrepo.com/
