### ISSUE TITLE
CREAR LA VISTA PARA ASISTENTES A UN EVENTO/ CREATE A VIEW FOR EVENT'S ATTENDANTS

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#117]
### EXPLANATION 

Después de haber ingresado a un evento, puede ver la vista de Editar Evento, al  seleccionar el boton "Asistentes" se desplegara una vista de pantalla donde se muestra la lista de asistentes a un determinado evento. Notar que el boton "Asistente" no debe verse en la vista de "Crear".

After clicking an event in the list, you should see the Edit View, selecting the "Asistentes" button will display a screen view where a table is displayed with the event attendants. Note that the button "Asistentes" should not be displayed on the "Create" view.

### SCREENSHOTS .

![Image](https://user-images.githubusercontent.com/111365000/186725721-2296eaa7-61ee-42f6-af9f-91dec3f8e046.png)

### Steps to show

1. Click 'Eventos'
2. Click any event
3. Click 'Asistentes'

### CHECKLIST.

- [ ] A path `eventos/asistentes/:id` must be generated to show the view.
- [ ] In the "Create" Event View there is NO button "Asistentes".
- [ ] In the "Edit" Event Vier there is a button "Asistentes".
- [ ] When you click the button "Asistentes" in the Edit view you are redirected to the view "Asistentes" (`eventos/asistentes/:id`, the `:id` should be the event's id).
- [ ] The aggregate information should be displayed in a table.
- [ ] Each attendant's information is in a row with the required data so that the user can see this information.
- [ ] There is a "X" red button, is you click on it you change the state of the Attendee to "Inactivo"

###  RELATED ISSUES.

https://xd.adobe.com/view/c3c8d408-317c-4f89-bd90-094f636b567a-969b/screen/65fffd79-b01e-407e-bf66-44ae231f721a/
pagina 3-17

**Comment by Eghinner** [comment]
@e-azocar Is this information available? the attendees of an event, I mean

**Comment by Israel-Laguan** [comment]
Done partially in https://github.com/Azordev/did-admin-panel/pull/195 any further changes will be in another issue
