### ISSUE TITLE
HACER FUNCIONAR LA OPCIÓN ELIMINAR EVENTO / TO MAKE THE DELETE EVENT OPTION WORK

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#118]
PROJECT TASK TEMPLATE.

### EXPLANATION

Después de haber  seleccionado "crear evento"  y llenar todos los datos  pedidos, podemos ver la opción eliminar el evento  cuando  le de clic  a"Eliminar" esta opción lo llevara a una vista de pantalla donde ; le volverá a preguntar si (Desea eliminar este evento ) dando paso a  un espacio  donde se debe escribir ELIMINAR si el usuario desea eliminar el evento.  También tendrá la opción de  aceptar y cancelar.

### SCREENSHOTS

![Image](https://user-images.githubusercontent.com/111365000/186735968-789534f7-e6c7-4ca3-853d-91e69edcfded.png)

### CHECKLIST.

En la vista de crear eventos en la parte inferior de la pantalla, estará la opción "Eliminar"  al  darle clic  debe aparecer un mensaje de confirmación  si deseo eliminar, aceptar o cancelar.

In the event creation view, at the bottom of the screen, there will be the "Delete" option. When you click on it, a confirmation message should appear asking if you wish to delete, accept or cancel.

### USE CASES

Si el creador del evento no llena el espacio requerido donde debe confirmar, el evento no se eliminara.

If the event creator does not fill in the required space where he/she must confirm, the event will not be deleted.

## Dependencies

- https://github.com/Azordev/did-admin-panel/issues/132 The modal should work in order to verify deletion

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

**Comment by Israel-Laguan** [comment]
Modal already exists, will re assign to @e-azocar to add functionality

**Comment by Israel-Laguan** [comment]
I added the call to remove event
