### ISSUE TITLE
HACER FUNCIONAR LA OPCIÓN ELIMINAR PARTICIPANTES DEL EVENTO/TO MAKE THE OPTION TO DELETE PARTICIPANTS OF THE EVENT WORK.

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#120]
PROJECT TASK TEMPLATE.

### EXPLANATION 

Una vez llenado los datos  del participante del evento y  dar clic en la opción "Eliminar" pantalla donde  nos  aparecerá un mensaje de confirmación  con un espacio donde  escribir ELIMINAR,  y las opciones de Aceptar y Cancelar.

Once the event participant's data has been filled in and click on the "Delete" option, a confirmation message will appear with a space to write DELETE, and the options to Accept and Cancel.

### SCREENSHOTS

![Image](https://user-images.githubusercontent.com/111365000/186738659-e0484863-bc47-4d61-a143-283b495617fc.png)

### CHECkLIST

Esta opción de eliminar participante  debe tener  un mensaje de confirmación  con un espacio  donde se escribe ELIMINAR si el usuario desea eliminar, ademas debe presentar dos opciones Aceptar y Cancelar. 

This option to delete a participant must have a confirmation message with a space where you write DELETE if the user wants to delete, it must also present two options Accept and Cancel. 

### USE CASES
Si el usuario no escribe ELIMINAR  en el espacio requerido  no se eliminara al participante.

If the user does not type DELETE in the required space, the participant will not be deleted.

## Dependencies

- https://github.com/Azordev/did-admin-panel/issues/132 The modal should work in order to verify the deletion

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

**Comment by JRS-Developer** [comment]
I'm going to wait for this pull request to be closed to continue this issue because it's almost the same modal.
https://github.com/Azordev/did-admin-panel/pull/179

**Comment by JRS-Developer** [comment]
@Eghinner @Israel-Laguan 

I noticed that the "participantes" view isn't made yet. So I think that it must be made before to be able to continue with this issue.

https://xd.adobe.com/view/c3c8d408-317c-4f89-bd90-094f636b567a-969b/screen/65fffd79-b01e-407e-bf66-44ae231f721a

**Comment by Israel-Laguan** [comment]
> I noticed that the "participantes" view isn't made yet. So I think that it must be made before to be able to continue with this issue.

It's done now, please check 

https://www.did-admin.tk/eventos/asistentes/9d88c10e-fe17-4896-be3a-96f8dac69ebf

The event "Reunion DID" is the only one with participants, and you can only add one using the app

**Comment by Israel-Laguan** [comment]
I pushed a commit to solve this, let's make a smoke test to check if worked
