### ISSUE TITLE
[TASK] CREAR OPCIÓN "AÑADIR PROVEEDOR" /  CREATE ADD PROVIDER OPTION

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#124]
PROJECT TASK TEMPLATE

create add provider option.

### EXPLANATION

Después de haber ingresado la información de añadir proveedor  y  seleccionar la opción guardar se mostrara una vista de pantalla con toda la información guardada, también debe estar  en la parte superior de la pantalla la opción "Añadir proveedor", su función sera  pedir una nueva información para ingresar un proveedor diferente

After having entered the information to add supplier and selecting the save option, a screen view will be displayed with all the saved information, the "Add supplier" option should also be at the top of the screen, its function will be to ask for new information to enter a different supplier.

### STEPS TO REPRODUCE:

1- Al llenar los datos requeridos en la vista de proveedor, vemos:
When filling in the required data in the supplier view, you see:

![Image](https://user-images.githubusercontent.com/111365000/186924344-f976d029-a00c-4274-844a-b6e17e3a77a0.png)

2- Se le da guardar.
You save the information

3- luego vemos esta vista:
then you see

![Image](https://user-images.githubusercontent.com/111365000/186925108-a6c0ca37-ce8e-4f27-b795-aaa2b25c1f8b.png)

4- en la parte superior de la pantalla vemos: crear este botón.

at the top of the screen we see: create this button.
![Image](https://user-images.githubusercontent.com/111365000/186925361-3f923348-8529-4972-90bd-68c171919774.png)

5. la función de este botón (añadir proveedor) es llevar nuevamente a una vista de pantalla para agregar otro proveedor.
 the function of this button (add supplier) is to take you back to a screen view to add another supplier.

![Image](https://user-images.githubusercontent.com/111365000/186760000-2c750332-9fe9-4024-b01f-fdc1f16fe351.png)

 ### CHECKLIST.

Debe estar la opción "Añadir proveedor" en la parte superior de la pantalla para ingresar un nuevo proveedor.

The "Add supplier" option should be at the top of the screen to enter a new supplier.

### USE CASE

La opción "añadir proveedor" debe tener una reacción al pasar el cursor ( subrayar).

The "add supplier" option should have a reaction when hovering the cursor ( underline).

**Comment by Eghinner** [comment]
https://github.com/Azordev/did-admin-panel/issues/108
