### ISSUE TITLE
[TASK] CREAR UN PAGINARIO PARA PROVEEDOR / CREATE A PAGINARY FOR SUPPLIERS.

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#126]
PROYECT TASK TEMPLATE:

Hacer paginario en la parte inferior de la pantalla.
Make a paginary in the bellow part of the view.

### EXPLANATION

En la vista de Añadir proveedor,  después de haber llenado los datos se selecciona la opción añadir  y nos muestra una vista de pantalla con un paginario en la parte inferior de la pantalla.

In the Add supplier view, after having filled in the data, select the add option and a screen view is displayed with a pager at the bottom of the screen.

### STEPS TO REPRODUCE:

1-En la vista de añadir proveedor vemos:
In the suppliers view you see

 ![Image](https://user-images.githubusercontent.com/111365000/186916077-fd85e78d-15b5-4117-b723-a5879e41e250.png)

2- Al llenar los datos que se piden y le doy la opción añadir, se despliega esta vista:
 When I fill in the requested data and click on the add option, this view is displayed:

 ![Image](https://user-images.githubusercontent.com/111365000/186767040-73b8ac3e-3279-4b7f-bf32-4bdd465b95c9.png)

3-En la parte inferior de la pantalla se puede ver este paginario:
Below of the page you can see this paginary.

![Image](https://user-images.githubusercontent.com/111365000/186767127-03bf705d-07cf-468e-8d1b-b8144aa7445f.png)

### CHECKLIST

Cuando se abre la vista al pulsar "Añadir" , debe haber en la parte de abajo un paginario para que el usuario pueda saber información del numero de proveedores inscritos en la pagina. Este paginario debe tener las opciones antes y siguiente, para retroceder o avanzar en cada pagina.

When the view is opened by clicking on "Add", there should be a paginary at the bottom of the page so that the user can know information about the number of suppliers registered on the page. This paginary should have the options before and next, to go back or forward in each page

**Comment by Eghinner** [comment]
@JuanParraIV you should do this. what do you think?

**Comment by JuanParraIV** [comment]
Ok
