### ISSUE TITLE
Add validation modal - product creation, editing and/or deletion view - añadir modal de validación - vista de creación, edición y/o eliminación de productos

### ISSUE THREAD

**Issue by angelik0828** [Azordev/did-admin-panel#132]
## This issue includes the functionality of the buttons, clicking remove should bring up a validation asking the user if they want to remove something similar to this design but related to the theme of the product.
 
![image](https://user-images.githubusercontent.com/4030477/186989797-d0d261c9-efd0-4708-a773-3f6444748730.png)

_Originally posted by @angelik0828 in https://github.com/Azordev/did-admin-panel/issues/95#issuecomment-1228942754_

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

**Comment by Israel-Laguan** [comment]
> ## Blocked while developing the event in the backend and creating a component for reuse.

Done by @e-azocar so I un block this issue

**Comment by Israel-Laguan** [comment]
I notice the modal already exists, will re assign to @e-azocar to add functionality

**Comment by Israel-Laguan** [comment]
I confirmed modal worked as expected, closing this issue
