### ISSUE TITLE
CREAR VISTA PARA LOS DATOS DEL PERFIL DE PROVEEDOR

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#138]
TASK CREAR VISTA PARA LLENAR LOS DATOS DEL PERFIL DE PROVEEDOR

### EXPLANATION

Al entrar con usuario y contraseña de proveedor
se abre una vista de pantalla con los siguientes datos a pedir 
primero arriba el botón : regresar  que regresa a la vista anterior donde  pide usuario y contraseña
segundo  logotipo de la empresa: tendrá un espacio para colocar el logo de la empresa
tercero nombre de la marca: tendrá un espacio para incluir el nombre de la marca de la empresa
cuarto link del catalogo : tendrá espacio para incluir el link del catalogo de la empresa
quinto las opciones  cancelar y guardar : función guardar  guarda la información y funcion eliminar elimina la información

 ### SCREENSHOTS 
1 Entro con usuario y contraseña de proveedor

![Image](https://user-images.githubusercontent.com/111365000/187234663-f2632af6-734e-438b-8c34-cbf261110d75.png)

2 Crear esta vista

![Image](https://user-images.githubusercontent.com/111365000/187234747-2be82a35-f39a-4872-a7e9-521731a4e953.png)

### USER STORY

Yo como usuario proveedor quiero que al entrar a crear mis datos de perfil en la parte superior quiero que este la opción regresar

Yo como usuario proveedor quiero que  al entra a ingresar mis datos  este un espacio para el logo de mi empresa

Yo como usuario proveedor quiero que al ingresar mis datos de perfil este un espacio  para el nombre de la marca

Yo como usuario proveedor quiero que aya un espacio para incluir el numero de whatsapp

Yo como usuario proveedor quiero que al ingresar mis datos aya un espacio para el link del catalogo 

 Yo como usuario proveedor quiero que al ingresar mis datos están  las opciones guardar y cancelar

### ACEPTANCE CRITERIAN
En esta vista se pedirán los datos  para el perfil de la empresa

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

**Comment by Eghinner** [comment]
> this problem already exists in #90
> 
> ## Doesn't have all the labels

No, Looks like a new view

**Comment by Eghinner** [comment]
I think you can develop this issue with admin, as usual, then implement the logic for a provider user.
## New criteria acceptance

- [ ] Add link 'Socios' to dashboard
- [ ] Create the path '/perfil`.
- [ ] Resolve just design

**Comment by JuanParraIV** [comment]
Esta tarea dice que no esta asignada se puede tomar?

**Comment by JuanParraIV** [comment]
Is Available?
