### ISSUE TITLE
(BUG) HACER FUNCIONAR LA OPCION NUEVO PROVEEDOR / to run the new supplier option

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#139]
BUG DID PAGE.

### EXPLANATION

Al añadir nuevo proveedor no se guarda la información, es decir no funciona la opción añadir nuevo proveedor.
When adding a new provider, the information is not saved, i.e. the add new provider option does not work.

### STEPS TO REPRODUCE

1- Visit: https://www.did-admin.tk/ingresar

2- Use credentials:
Usuario: QA00000002
Contraseña:00000002

3-You can see this, y selecciono proveedores.

![Image](https://user-images.githubusercontent.com/111365000/186944831-5f1f8e30-0aaa-4021-b50a-45c5878501b0.png)

4- podemos ver esta vista. selecciono añadir nuevo proveedor. 
 we can see this view. select add new supplier.

![Image](https://user-images.githubusercontent.com/111365000/186945118-85ed643e-b89d-46e9-a6b6-012cca2d6542.png)

5-se abre esta vista:
this view opens:

![Image](https://user-images.githubusercontent.com/111365000/186945280-8ce20be3-e1e0-4fd2-98b7-10e7aef06a12.png)

6- ingreso los datos que se piden ahí .
 I enter the data requested there

![Image](https://user-images.githubusercontent.com/111365000/186946135-b8df2084-cda3-465d-8550-0ec406be1735.png)

7- al darle clic a enviar vemos que el nuevo proveedor añadido no se agrego.
When we click on send we see that the new supplier added has not been added.

![Image](https://user-images.githubusercontent.com/111365000/186946837-d2f5d14f-1d85-4a7a-9b6d-c306efa5da25.png)

### DEVICE AND OS

HP Laptop 14-dq1xxx
Desktop: Fluxbox 1.3.7 info: tint2 vt: 7 dm: LightDM 1.26.0 
Distro: MX-21.1_fluxbox_x64 Wildflower April 9  2022 
Chrome 103.0
Resolution: 1366x766

### LINKS:

https://www.did-admin.tk/ingresar
https://www.did-admin.tk/proveedores/crear
https://www.did-admin.tk/proveedores

### EXPECTED BEHAVIOR
When enter to the add provider option, this option works in right way and it can add the new provider.

Cuando se entre a la opción añadir proveedor, y al seguir cada paso funcione la opción y añada al proveedor que se quiere agregar.
When you enter the add supplier option, and following each step, click on the option and add the supplier you want to add.

### ACTUAL BEHAVIOR.
THE OPTION ADD NEW PROVIDER DOES NOT WORK, IT DOES NOT SAVE THE NEW PROVIDER.

### EXAMPLE

/home/lina/Descargas/www_screencapture_com_2022-8-26_11_53.mp4

https://user-images.githubusercontent.com/111365000/186954671-c7803648-2fad-4a07-b238-30129a49f9ba.mp4

**Comment by Eghinner** [comment]
wait while https://github.com/Azordev/did-admin-panel/issues/90 it closes

**Comment by Eghinner** [comment]
Close for this https://github.com/Azordev/did-admin-panel/issues/90
