### ISSUE TITLE
CREAR LA OPCIÓN "AÑADIR NUEVO PRODUCTO"

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#147]
TASK CREAR LA OPCIÓN AÑADIR NUEVO PRODUCTO.

### EXPLANATION

Al entrar como usuario proveedor se abre una vista de pantalla con las opciones "Perfil"y "Productos" selecciono productos se abrirá una vista de pantalla con una  lista de productos ya agregados y en la parte superior de la pantalla estará la opción "Añadir nuevo producto", crear la opción "Añadir nuevo producto" 
La acción es llevar a una vista de pantalla donde debe agregar unos datos para que el producto quede agregado a la lista de producto

1- Entro con usuario proveedor y contraseña

![Image](https://user-images.githubusercontent.com/111365000/187491017-e340104c-09ef-46c3-9157-acb87d110e23.png)

2- Selecciono productos

![Image](https://user-images.githubusercontent.com/111365000/187491144-f846bcc0-86ef-4df1-b019-67de08ccbef9.png)

3- Crear esta opción "Añadir nuevo producto" y su función

![Image](https://user-images.githubusercontent.com/111365000/187491471-f7a68747-a5bc-4a09-8b76-56606cc37ef3.png)

### USER STORY
Yo como usuario proveedor quiero que al entrar a la opción productos, haya  una opción "Añadir nuevo producto" para poder ingresar un nuevo producto.

Yo como usuario proveedor al seleccionar la opción "Añadir nuevo producto" se abra una  vista de pantalla donde pueda llenar los datos de nuevo producto.

Al seleccionar la opción "Añadir nuevo producto" se abre una vista de pantalla con los siguientes requisitos para  añadir el producto.
CREAR  LAS SIGUIENTES OPCIONES 
"Regresar" función volverá ala  vista anterior de pantalla donde están los  productos agregado.
"Nombre del producto" tendrá un espacio para ingresar el nombre del producto.
"Precio del producto" tendrá un espacio para el precio del producto
"Descripción del producto" tendrá un espacio para la descripción del producto
"Añadir imagen del producto" tendrá un espacio para la imagen del producto
"Guardar" y "Eliminar" guarda la información o eliminar eliminara la  información.

 ### SCREENSHOTS

![Image](https://user-images.githubusercontent.com/111365000/187507498-729233f6-b571-40d6-9af5-258e47fccc2b.png)

 ### USER STORY

Yo como usuario proveedor quiero que al seleccionar la opción "Añadir nuevo producto" este la opción "Regresar" para volver a la pagina anterior

Yo como usuario proveedor quiero que al seleccionar la opción "Añadir nuevo producto" este la opción "Nombre del producto" para ingresar el nombre del producto a ingresar

Yo como usuario proveedor quiero que al seleccionar la opción "Añadir nuevo producto" este la opción "Precio del producto" para ingresar el precio del producto

Yo como usuario proveedor quiero que al seleccionar la opción "Añadir nuevo producto" este la opción "Imagen del producto" para poder ingresar la imagen del producto

Yo como usuario proveedor quiero que al seleccionar la opción "Añadir nuevo producto"

Yo como usuario proveedor quiero que al seleccionar la opción "Añadir nuevo producto" este la opción "Guardar"estará  ce color verde guarda la información agregada y la opción "Eliminar estará de color rojo y eliminara la información agregada.

**Comment by Eghinner** [comment]
Solve here https://github.com/Azordev/did-admin-panel/issues/88
