### ISSUE TITLE
CREAR LOS ESTADOS DE LOS BOTONES EN LA BARRA LATERAL DONDE ESTÁN LAS OPCIONES

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#163]
### EXPLANATION

Cuando ya  haya ingresado con usuario y contraseña se abre la primera  vista con una barra lateral  donde están las opciones:
- Eventos
- Socios
- Proveedores

Cuando se selecciona una de estas opciones debe estar en color blanco mientras este seleccionada, en cambio las otras estarán en color  gris.

### SCREENSHOTS

![Image](https://user-images.githubusercontent.com/111365000/187928060-ca2a2b5d-9275-407f-8e2c-12ffa93f214c.png)

### CHECKLIST 

- [ ] La opción seleccionada debe estar en color blanco.

- [ ] Se mostraran en gris las opciones que  no están en selección cuando ya este seleccionada una de ellas

link abode XD

https://xd.adobe.com/view/c3c8d408-317c-4f89-bd90-094f636b567a-969b/screen/43b8eba9-aafe-4adb-b764-f424c98724e3/

**Comment by Eghinner** [comment]
repeated https://github.com/Azordev/did-admin-panel/issues/67
