### ISSUE TITLE
Make Add Product Form Functional **Edit: Just add image**

### ISSUE THREAD

**Issue by Eghinner** [Azordev/did-admin-panel#168]
**Is your feature request related to a problem? Please describe.**
When I am in the product form, and I fill in all the fields, I get an error when saving.

### Acceptance Criteria

- [ ] 'Nombre' and 'Precio' is obligatory
- [ ]  When an image is entered it is displayed
- [ ] When you click save, the information is saved in the database.
- [ ] When you click save, I am redirected to all products.

**Design**
![chrome_OqWnktaiS0](https://user-images.githubusercontent.com/71513679/188321625-5cab1da0-099b-4182-acee-14b032bd93a1.png)

### Steps to show

1. Go to 'Proveedores'
2. Click any provider
3. Click Añadir nuevo producto

### Ref for api request and endpoint

- controllers\products.ts
- pages\api\products\index.ts

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

**Comment by Eghinner** [comment]
Blocked meanwhile https://github.com/Azordev/did-admin-panel/pull/136 is not closed

**Comment by Israel-Laguan** [comment]
User for a provider:
Username:
`00ROLLUX`
Password:
`ROLLUX`

**Comment by Israel-Laguan** [comment]
> Blocked meanwhile #136 is not closed

Closed, so please go ahead @yanfranve

**Comment by angelik0828** [comment]
i think the path is

1. login
2. providers
3. new provider

![imagen](https://user-images.githubusercontent.com/4030477/189754418-df56f5d0-ecfc-41df-b196-03523aad99a9.png)

**Comment by Eghinner** [comment]
@PrototypeK02 sorry, is done
