### ISSUE TITLE
CREAR VISTA  FORMULARIO DE NUEVO EVENTO

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#172]
### EXPLANATION

Al comparar el diseño en la vista de "crear nuevo evento", podemos notar que no coincide con el diseño asignado .
Por lo tanto , se debe crear esta vista con el diseño asignado.

### SCREENSHOTS

Current design. 

![Image](https://user-images.githubusercontent.com/111365000/188494254-f9aa670b-86f9-4079-80a3-4edfda0676b3.png)

Expected design

![Image](https://user-images.githubusercontent.com/111365000/188494424-349e57d5-4bd8-4c35-a2b6-44d252dfe779.png)
  
### TASK TO DO

1- Crear el botón regresar, su función debe ser regresar a la  vista anterior es decir a Eventos este botón estará en la parte superior de la pantalla

2- Crear un logo de asistentes color azul

3- Crear un espacio con el nombre del evento

4 -Crear un espacio para la fecha del evento

5 Crear un espacio para la descripción del evento

6 -Crear un espacio para el limite de asistentes

7- Crear un espacio para el botón convocatoria,  su función sera la de definir si hay convocatoria o no.

8 -Crear un botón para añadir  pdf su función sera llevarte  a la lista de archivos para seleccionar un pdf para mostrar

9 -Crear la opción  guardar  su función sera guardar la información agregada para crear el evento

10 - Crear la opción cancelar, su función  cancela el evento agregado

11- Crear la opción eliminar, su función sera eliminar la información y el evento

### HISTORIAS DE USUARIO A CUMPLIR

Como  usuario, me gustaría que en la vista de pantalla de crear eventos haya la opción Regresar.

Como  usuario, me gustaría que hubiera un logo de asistentes.

Como  usuario, me gustaría que hubiera un espacio donde escribir el nombre del evento

Como  usuario,  me gustaría que haya un espacio para escribir la fecha del evento.

Como  usuario, me gustaría que haya un espacio que haga una descripción acerca del evento a realizar. 

como  usuario, quisiera que haya un espacio para el limite de asistentes al evento.

Como usuario, me gustaría que haya un botón que indique si hay o no convocatoria.

Como usuario, me gustaría que en esta vista hubiera una opción para subir archivos pdf.

Como usuario, me gustaría que después de haber ingresado la información haya la opción Guardar para guardar todos los datos requeridos.

Como usuario, me gustaría que haya la opción cancelar, por si deseo cancelar o corregir información del evento.

Como usuario, me gustaría que haya la opción Eliminar por si deseo eliminar la información escrita.

### STEPS TO REPRODUCE:

1- Ingreso a la pagina DID con usuario y contraseña.
2- Selecciono Eventos.
3- Selecciono crear nuevo evento.

### REFERENCES

https://www.did-admin.tk/eventos/crear

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

**Comment by angelik0828** [comment]
## ⚠️ Programmer take into account

## When clicked, it should submit the existing form to create a new event and fill in the data with the information we are querying about the event.

**Comment by Israel-Laguan** [comment]
Currently it looks like this
![image](https://user-images.githubusercontent.com/36519478/189565227-9000bad3-ea70-4ef6-86ff-4b4226b6f160.png)

**Comment by Israel-Laguan** [comment]
I used the form from https://github.com/Azordev/did-admin-panel/pull/195 to make this easier

**Comment by heliomar-pena** [comment]
Currently it looks like this:
![imagen](https://user-images.githubusercontent.com/66505715/190227602-cf01d852-d7a6-4e8b-9663-5e17fd7667ed.png)

**Comment by Israel-Laguan** [comment]
The "Asistentes" and "Eliminar" buttons are not needed is this view

**Comment by Israel-Laguan** [comment]
I notice it lacks the field "Limite de asistentes"

I just added the field in Hasura
![image](https://user-images.githubusercontent.com/36519478/190235979-4b3ca8b9-a07b-40c4-a84f-3fe731db5d3b.png)

But I notice this field is not used in any other place
