### ISSUE TITLE
Hovering over the menu texts changes color.

### ISSUE THREAD

**Issue by Eghinner** [Azordev/did-admin-panel#183]
## Acceptance Criteria
- [ ] Define by default each link with gray color (my suggest, opacity: .7)
- [ ] When a view is active, its link changes to white.
- [ ] When hovering, change to white

![image](https://user-images.githubusercontent.com/4030477/186268561-1f3921f8-1216-4159-9698-f5db846ccc27.png)
![image](https://user-images.githubusercontent.com/4030477/186269748-89ce066b-0c09-49d9-b4dc-41d8ff0127c6.png)

_Originally posted by @angelik0828 in https://github.com/Azordev/did-admin-panel/issues/67#issuecomment-1224907119_

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

**Comment by JRS-Developer** [comment]
@Eghinner @Israel-Laguan 
Hello, I have finished the first and third issue. 

I have a question about the second. Should it match the exact url or it should match nested links as well?

Nested:

https://user-images.githubusercontent.com/77207702/188961599-a9df4ffd-86c9-4b0a-ad92-9dd32298120e.mov

Exact match:


https://user-images.githubusercontent.com/77207702/188962008-6b642c6a-f53f-491a-8210-c50d43f9235b.mov
