### ISSUE TITLE
Corregir el diseño del formulario "Añadir socio" y sus funciones

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#184]
### EXPLANATION 

Si comparamos el diseño de la vista "Añadir socio" se puede notar que no coincide con el diseño asignado, hay que centrar mas el el marco que quede mas centrado .

Falta agregar la opción regresar que esta en la parte superior de la pantalla y  su función sera volver a la vista anterior (Socio).
falta la función de las opciones   "Añadir"  "Eliminar" y su función correspondiente.

Eliminar su  función , al darle clic a eliminar este te mostrar una vista con un mensaje de comfirmacion que te pregunta si deseas eliminar

Añadir su función, al ver llenado todos los datos y darle clic en añadir guardara la información agregandote al grupo de socios

#### SCREENSHOTS

Diseño actual. No tiene la opción regresar centrar mas el marco de la informacion
![image](https://user-images.githubusercontent.com/111365000/188966800-e8cd2976-5508-4307-b485-915f720260a2.png)

Diseño asignado

![image](https://user-images.githubusercontent.com/111365000/188966653-c755d0fd-e46d-497e-a1cc-3d9888d4bd68.png)

Diseño asignado. Al darle clic eliminar mostrara la siguiente vista con un mensaje de comfirmacion

![image](https://user-images.githubusercontent.com/111365000/188968383-7788fd4e-d0ac-49f9-b2ae-74ec7d94aba9.png)

### USER STORIES TO FULFILL

Como usuario quiero que  el espacio de la información este mas centrado

como usuario quiero que la opción Añadir funcione guardando la información
 
como usuario quiero que la opción Eliminar funcione como esta estimulada

como usuario quiero que este la opción regresar y  funcione llevando al a vista anterior (socio)

## Dependencies

- https://github.com/Azordev/did-admin-panel/issues/132 The modal should work in order to verify the deletion

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

**Comment by angelik0828** [comment]
@Eghinner @Israel-Laguan I think the effort estimate for this task is too high.

**Comment by angelik0828** [comment]
## I just checked and the idea is to leave the functional form with the delete modal, be guided how the delete is in the event view and leave it with those validations, you can follow these steps

- Event
- Click event
- Remove


![image](https://user-images.githubusercontent.com/4030477/189183048-b85baba6-84b0-4edf-9cd5-8bc2290171de.png)

![image](https://user-images.githubusercontent.com/4030477/189183128-b1432111-c1d1-42cc-a5c0-18f8fe84f4e0.png)

![image](https://user-images.githubusercontent.com/4030477/189183200-167ea025-3e75-42b9-9dbe-370c5c9a46a2.png)

**Comment by Israel-Laguan** [comment]
> @Eghinner @Israel-Laguan I think the effort estimate for this task is too high.

Let's keep the EE to foster participation, as is high priority
