### ISSUE TITLE
Función de la opción asistentes  vista de asistentes

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#191]
# EXPLANATION 

Al entrar a la vista  eventos y seleccionar un evento se  abre una vista donde se muestra un formulario,se encuentra una opción (Asistentes) , al seleccionar esta opción, su función sera llevarme a una vista  de pantalla donde se muestran los datos de algunos asistentes ya registrados en esta vista de pantalla estará la opción regresar en la parte superior de la pantalla y su función sera regresar a la vista anterior (formulario)

## SCREESHOTS

 Seleccionar  la opción asistentes
![image](https://user-images.githubusercontent.com/111365000/189183860-157a4983-1bc7-45b4-b401-f2fd949e1a1d.png)

Vista de pantalla que se abrirá como función de la opción (Asistentes)

![image](https://user-images.githubusercontent.com/111365000/189184059-408cad3f-2214-4aed-94a1-b175cfcaddf8.png)

## Design
https://xd.adobe.com/view/c3c8d408-317c-4f89-bd90-094f636b567a-969b/screen/1588e0a1-6dbb-4be3-8412-0b4bf0ad98fa/

## Flujo de trabajo

acceso - Eventos - Selecciono un evento - formulario - opción asistentes 
  
## Historias de usurario

como usuario quiero que al seleccionar la opción asistentes me lleve a una vista donde salga la información de asistentes agregados

## Checklist

- [x] In the "Create" Event View there is NO button "Asistentes".
- [x] In the "Edit" Event Vier there is a button "Asistentes".
- [x] When you click the button "Asistentes" in the Edit view you are redirected to the view "Asistentes" (`eventos/asistentes/:id`, the `:id` should be the event's id). **This view can be empty for this Issue to be accepted.**

## Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

**Comment by angelik0828** [comment]
@e-azocar attendee list view does not exist has to be created
