### ISSUE TITLE
hacer la funcion de editar proveedor

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#201]
###  EXPLANATION
Al ingresar con usuario y contraseña al admin panel did ,se abre una vista de pantalla "Eventos" , selecciono la opción "Proveedores" ,se muestra una vista de pantalla con una lista de proveedores ya ingresados (de forma horizontal ) y en el extremo derecho se ve un símbolo que significa editar al darle clic su función sera llevarte a una vista de pantalla donde esta el mismo formulario de añadir proveedor

# Pasos a seguir

Entro con usuario y contraseña-selecciono "Proveedores" - selecciono el botón editar

# SCREENSHOTS 
1  Diseño asignado donde se puede ver el botón editar

![image](https://user-images.githubusercontent.com/111365000/189733278-d7eceb04-2040-474e-9d95-5ea22fc490ac.png)

2 Botón editar hacer la función de este botón
![image](https://user-images.githubusercontent.com/111365000/189733775-9435e7fa-5523-49bb-9d49-a477eb1f47f4.png)

3 Vista de pantalla que al darle clic lleva el boton editar 

![image](https://user-images.githubusercontent.com/111365000/189734286-7b538403-948e-46f2-a07a-d458a99779d8.png)

# USER STORY

Como usuario quiero que al darle clic al botón editar me lleve al formulario de añadir proveedor

**Comment by angelik0828** [comment]
Add the styles to the vendor form
Reference desing: 
https://xd.adobe.com/view/c3c8d408-317c-4f89-bd90-094f636b567a-969b/screen/4a14fc8d-f6f4-4054-a358-341e13cd428f/
