### ISSUE TITLE
## ❌ The create product button is not there validate what happened

### ISSUE THREAD

**Issue by angelik0828** [Azordev/did-admin-panel#202]
## ❌ The create product button is not there validate what happened
-When you click create product, the product creation form should appear

![imagen](https://user-images.githubusercontent.com/4030477/189743285-dde68ae7-0c59-4706-b533-dd69a89bf574.png)

**Expected result** 

1. ![imagen](https://user-images.githubusercontent.com/4030477/189743705-8a9ca108-2021-4222-81b8-8bf96d84775c.png)
2. ![imagen](https://user-images.githubusercontent.com/4030477/189744103-5b06c896-63dc-4fb2-8fe0-137ad8ae4129.png)

**link reference**

https://xd.adobe.com/view/c3c8d408-317c-4f89-bd90-094f636b567a-969b/screen/4aa022ee-e201-4535-bab2-6cfb2a32e65e/

_Originally posted by @angelik0828 in https://github.com/Azordev/did-admin-panel/issues/193#issuecomment-1244307204_

**Comment by Eghinner** [comment]
@PrototypeK02 sorry, is done
