### ISSUE TITLE
Crear una diferencia de Ingreso como proveedor y ingresar como usuario Admin

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#205]
# EXPLANATION

Al ingresar con su credencial de proveedor el admin panel ya debe tener la información en la base de datos para poder ingresar como proveedor y  tener  acceso a perfil 

# SCREENSHOTS
 1 Si ingresa como  proveedor puede ver ver su perfil o crear su perfil puede  añadir productos 

![image](https://user-images.githubusercontent.com/111365000/189749323-6c997b58-81b2-49c7-9406-c1ff927b435a.png)

 2 Este proveedor ya esta en la base de datos y el al ingresar como proveedor, ingresa y ve su perfil las credenciales de usuario no dan acceso a perfil de provedor

![image](https://user-images.githubusercontent.com/111365000/189749571-ed51e13c-2510-4087-81e1-60dc594dcc92.png)

# USER STORY
 
Como proveedor quiero tener acceso a perfil de proveedores

No es igual ingresar como usuario administrador a ingresar como proveedor

ingresar como proveedor me abre una vista de pantalla a un perfil de proveedor

**Comment by angelik0828** [comment]
## ✔️ this was done yesterday, now it is possible to log in as supplier user
