### ISSUE TITLE
crear funcionalidad del perfil de provedor

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#206]
# EXPLANATION 

Al ingresar con credenciales de proveedor se abre una vista d pantalla donde esta un formulario ,este formulario se debe llenar con los datos para crear un perfil como proveedor pero al ingresar los dato no guarda la información no guarda el imagen  no tiene funcionalidad

# SCREESHOTS

1 Diseño asignado esta es la vista de pantalla de perfil
![image](https://user-images.githubusercontent.com/111365000/189752944-8e61e8d1-5e39-4be9-97c7-fd10df746fb2.png)

2 Crear la  funcionalidad de logotipo al ingresar un imagen debe guardarse y mostrarse cuando se guarde la infomacion como un logotipo de la empresa en su perfil

![image](https://user-images.githubusercontent.com/111365000/189754249-eab3ec73-fbc3-4977-bbeb-64643cb83878.png)

3 las validaciones  "Cancelar" y "Guardar" deben funcionar

# USER STORY 
Como proveedor quiero ingresar una imagen como logo de la empresa

Como proveedor quiero crea mi perfil al seleccionar la opción "Guardar"

**Comment by angelik0828** [comment]
## ⚠️ @PrototypeK02 This task is urgent, I appreciate your collaboration if it is possible for today.

**Comment by PrototypeK02** [comment]
Hi Victor, I've been working on this issue, and then realized I was modifying the wrong file. Can you please let me know the path of this file so I can finish it as soon as possible?

**Comment by heliomar-pena** [comment]
> Hi Victor, I've been working on this issue, and then realized I was modifying the wrong file. Can you please let me know the path of this file so I can finish it as soon as possible?

Hi, where I live we're without energy power, so I'm from the phone and can't check fine, but please check if this is the file that you're searching:

https://github.com/Azordev/did-admin-panel/blob/dev/components/ProfileForm/index.tsx

Let me know if it works for you

**Comment by heliomar-pena** [comment]
Good luck @PrototypeK02 ! Let me know if you need any help
