### ISSUE TITLE
Add sweetaler2 event when save something

### ISSUE THREAD

**Issue by Eghinner** [Azordev/did-admin-panel#214]
For a better user experience, every time something is saved through a form it should show an alert notifying the event.
![chrome_l9BjMGYNNN](https://user-images.githubusercontent.com/71513679/190160922-3a3397ca-a65c-4816-90ce-befa1c9028ab.gif)

**Comment by angelik0828** [comment]
## you can use a validation window to show the creation confirmation using a check in the center and a text below the icon that says created for a few seconds.

**Comment by eduardoquispe** [comment]
#248
