### ISSUE TITLE
error en paginario

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#216]
# Describe the bug
Encontramos que en la opción proveedores de did admin panel se ve una lista de proveedores ya ingresados y  el paginador  que informa los proveedores se mueve  al girar el maus , al darle clic ala flecha derecha del paginador para ver mas proveedores agregados no cambia sigue mostrando los mismos

# To Reproduce
--

1. Go to '...'ingreso con usuario y contraseña 
2. Click on '....' pantalla principal (Eventos) 
3. Scroll down to '.... selecciono proveedores'
4. See error se puede notar que al mover maus hacia abajo  también se mueve el paginador , no cambia la informacion al darle clic a la flecha derecha del paginador

# Screenshots

https://user-images.githubusercontent.com/111365000/189997782-d0637629-6dd8-46cd-b377-5a89b02ed8c9.mp4

# Expected behavior
  
El paginador debe quedarse sin movimiento en la parte inferior de la pantalla
 Al darle clic hacis la fecha  derecha debe cambiar los resultados de los proveedores ya que no cambian sigen siendo igual
**Desktop (please complete the following information):**

-

**Comment by Eghinner** [comment]
@JuanParraIV can you review this?
