### ISSUE TITLE
Error al dejar sin la opción "Cancelar" en "Añadir proveedor"

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#217]
# Describe the bug
Al ingresar con usuario y contraseña en did admin panel se abre la vista principal "Eventos" selecciono la opción "Proveedores" y le doy clic al botón "Crear nuevo proveedor"se muestra una vista de pantalla con formulario para ingresar el nuevo proveedor notamos que no existe la opción "Cancelar" que su función seria anular la información agregada

# To Reproduce

1. Go to '...'ingreso con usuario y contraseña
2. Click on '....'selecciono la opción "Proveedores"
3. Scroll down to '....'doy clic en el botón "Crear nuevo  proveedor"
4. See erroresta el formulario y en la parte inferior  solo se encuentra la opción "Añadir" solo .Debe estar también la opción "Cancelar"y con su función que es anular la información agregada

# Screenshots
1 Notamos que solo esta la opcion "Añadir"
![image](https://user-images.githubusercontent.com/111365000/190004086-3c862ff8-ee4b-4e71-8a9c-cf51c47c5135.png)

2 en este caso ya no seria Eliminar si la opción  Cancelar

![image](https://user-images.githubusercontent.com/111365000/190004347-defe3b77-edda-49d0-a1b9-81bfce9c41a9.png)

# Expected behavior
Esta vista de pantalla tendrá en la parte inferior de la pantalla la opción "Añadir" y "Cancelar

**Comment by PrototypeK02** [comment]
task done in issue #168
