### ISSUE TITLE
Show created product

### ISSUE THREAD

**Issue by Eghinner** [Azordev/did-admin-panel#221]
When a product is created, we cannot see the product created.
![chrome_hGPE6Y7urO](https://user-images.githubusercontent.com/71513679/190659926-d535bce7-47a3-4264-b644-8ecc3553ef3d.gif)
In this example I added a product with name Ronnan, but not appear in the list

**Comment by eduardoquispe** [comment]
@Eghinner The products are displayed sorted by name and paginated, the first 24 products are displayed, I could make a pagination or an infinite scroll.

**Comment by eduardoquispe** [comment]
Hello, what would need to be implemented to correct this bug, an infinite scroll, a pagination or would there be another proposal?

**Comment by angelik0828** [comment]
@eduardoquispe I think that the infinite scroll is not a very good idea, at least not for the user, he would not know how much he has left to see, we could think of a page that allows the user to know how many products he has left.

**Comment by Eghinner** [comment]
> Hello, what would need to be implemented to correct this bug, an infinite scroll, a pagination or would there be another proposal?

can you check if it always shows the last product added?

That should be the bug

**Comment by eduardoquispe** [comment]
@Eghinner shown in alphabetical order to what I have reviewed

**Comment by angelik0828** [comment]
## :warning: Is not showing the product I just created

![image](https://user-images.githubusercontent.com/4030477/190660826-1530c1c3-b520-45d0-8df0-8f528331319c.png)

- This appears in the console

![image](https://user-images.githubusercontent.com/4030477/190660942-b1e3f086-3024-4942-84d0-69185708b88c.png)

**Comment by eduardoquispe** [comment]
@angelik0828 only the first 24 are shown

**Comment by angelik0828** [comment]
## @eduardoquispe If pagination is necessary, but when creating the product it must appear in another way, the last created first.

- Let yourself be guided by the aspect of the design of the provider view.

![image](https://user-images.githubusercontent.com/4030477/190662696-3bb1637d-b898-4a1a-b83b-ec2f706e8f22.png)

**Comment by Franceliis** [comment]
@eduardoquispe Necesitamos esta tarea para hoy eduardo, crees que puedas?

**Comment by eduardoquispe** [comment]
#263
