### ISSUE TITLE
Validaciones mas separadas 

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#233]
**Describe the bug**
al ingresar como  proveedor a did admin panel y darle clic a la opción "Añadir nuevo producto" se muestra  un formulario para ingresar nuevo producto y en  ala parte inferior están las validaciones "Guardar y Eliminar", notamos que están muy juntas se debe separar un poquito mas una de otra

**To Reproduce**
Ingreso con nombre de proveedor y contraseña- selecciono la opción añadir nuevo producto - formulario parte inferior

**Expected behavior**
Separar un poquito la opción "Guardar" de la opción "Eliminar"

**Screenshots**
1 formulario donde se encuentra las validaciones "Guardar" y "Eliminar"

![image](https://user-images.githubusercontent.com/111365000/190254424-5cf0e068-9843-4486-be41-e2b96a3602af.png)

2 Separar un poquito estas vaidaciones
![image](https://user-images.githubusercontent.com/111365000/190254524-dc0668d3-f3c6-41be-bfa3-41dae227600e.png)

**Comment by heliomar-pena** [comment]
Please check if is ok now or if needs more space

![imagen](https://user-images.githubusercontent.com/66505715/190259006-5c96ff74-d1c2-48d1-8243-864fa4df3005.png)
