### ISSUE TITLE
Create empty field validations in event creation form and form of  creation of partners

### ISSUE THREAD

**Issue by angelik0828** [Azordev/did-admin-panel#253]
**Explanation**

when creating an event, and not filling in any field and clicking save, there must be validation of empty fields.
It should appear below the text field that the field is empty this for
- Name
- Date
- Hour
- All fields are required

take as a guide the validation of other forms

![image](https://user-images.githubusercontent.com/4030477/190678303-2c702d56-ff48-4eae-bf0d-2ad0d1b8e64b.png)

![image](https://user-images.githubusercontent.com/4030477/190680182-a87e25fa-c0b8-4a4d-9096-0d0a998d4fd8.png)

**Comment by angelik0828** [comment]
@PrototypeK02 How is this task going?

**Comment by PrototypeK02** [comment]
I was fixing some bugs in other issue, Im about to start with this, but it has no EE label

**Comment by PrototypeK02** [comment]
@Eghinner can you please consider EE-2 ? its not just about validate empty fields but also add a function for dates validation, and you are asking to validate 2 forms.

**Comment by PrototypeK02** [comment]
As said earlier, please consider EE-2 for this issue. @angelik0828  @e-azocar
