### ISSUE TITLE
Error al cancelar o guardar  información de prfil en did admin panel proveedor

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#255]
**Describe the bug**
Al ingresar con credenciales en did admin panel proveedor , al seleccionar la opción "Perfil" se abre una vista de pantalla con el formulario que  tiene la información del perfil agregado,  notamos que las validaciones  cancelar y guardar no funcionan correctamente al darle clic en cancelar notamos que se devuelve a la vista de productos y no cancela la información agregada, y lo mismo pasa al darle clic en la opción guardar.

**To Reproduce**
ingreso con credenciales proveedor - selecciono perfil - formulario ya completado - cancelar y guardar

**Expected behavior**
al ingresar la información requerida por el formulario y darle clic en la validación cancelar debe cancelar la información agregada 

**Screenshots**

https://user-images.githubusercontent.com/111365000/190680600-ce8e21bf-0c53-41c6-b19a-e02b65ad31c1.mp4

# Historias de usuario a cumplir 
 como proveedor quiero que al ingresar mi informacion el formulario de  perfil y le cancelar  pueda canclar la informacion y que  me este llevando a la vista de productos

# Check list
corregir la función de las validaciones cancelar

**Comment by Eghinner** [comment]
@PrototypeK02 is this bug present?

**Comment by PrototypeK02** [comment]
This bug was fixed in #206
