### ISSUE TITLE
In the Supplier user you should update the header data.

### ISSUE THREAD

**Issue by Eghinner** [Azordev/did-admin-panel#270]
### Actual Result
When updating the Supplier profile, the company logo image in the header does not change.
![chrome_pTnWK2FLij](https://user-images.githubusercontent.com/71513679/191044502-290d0fcb-8f7c-45bc-be80-04d311fb6d8e.gif)

### Expected
When updating the supplier profile to immediately change the header logo

#### Extra task
Logo size changes in different views
![chrome_aSE1gvzeOu](https://user-images.githubusercontent.com/71513679/191049084-a6494254-6252-459d-934b-5161e00d1dff.gif)

**Comment by Eghinner** [comment]
Meanwhile https://github.com/Azordev/did-admin-panel/pull/249

**Comment by Eghinner** [comment]
@eduardoquispe , Can you wait while this Pull closes https://github.com/Azordev/did-admin-panel/pull/249?

**Comment by eduardoquispe** [comment]
@Eghinner Yes, sorry, I didn't realize that the task was blocked.

**Comment by eduardoquispe** [comment]
@Eghinner Should the image be the same size in the different views or should it stay as it is now?

**Comment by Eghinner** [comment]
> Should the image be the same size in the different views or should it stay as it is now?

It must have the same size. That is, change it as it is now
