### ISSUE TITLE
ERROR AL NO MOSTRAR EL IMAGEN DE EVENTO SELECCIONADO

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#272]
**Describe the bug**
al entrar a did admin panel como usuario se abre una vista de pantalla  eventos ,selecciono un evento se abre una vista de pantalla donde se muestran los datos del evento pero no muestra el imagen del evento que en la parte principal se ve normalmente

**To Reproduce**
entro con credenciales usuario - eventos - selecciono un evento - se ven los datos del producto seleccionado pero muestra el imagen que  se veía en la parte principal

**Expected behavior**
Al seleccionar el evento y mostrar sus datos tambien debe mostrar el imagen agregado al evento seleccionado

**Screenshots**

[Screen Recording - Made with FlexClip (1).webm](https://user-images.githubusercontent.com/111365000/191059188-39f24144-9ef1-4f7e-8239-d2e4a6342c73.webm)

# user stori 
como usuario quiero que al seleccionar un evento y mostrar sus dato también pueda ver el imagen que esta en la lista de exibicion

**Comment by Eghinner** [comment]
Solve just with https://github.com/Azordev/did-admin-panel/issues/271
