### ISSUE TITLE
Add pagination on event page

### ISSUE THREAD

**Issue by angelik0828** [Azordev/did-admin-panel#284]
Explanation

When entering the events page, a very extensive list is seen, the ideal is that the user can manage the number of events that he wants to see, the change must be made and take as a basis the way in which the pagination is handled on the page of the product.

**Current**

![image](https://user-images.githubusercontent.com/4030477/191782644-e764b1c7-748a-470d-a617-dd1988068284.png)

**Expected result**

![image](https://user-images.githubusercontent.com/4030477/191782790-bd73f97b-cf1d-468f-9c19-d609c698b725.png)

Check list

- [ ] Add pagination on event page

**Comment by Eghinner** [comment]
@eduardoquispe could you do this like https://github.com/Azordev/did-admin-panel/pull/263?

**Comment by eduardoquispe** [comment]
@Eghinner Yes, no problem

**Comment by Israel-Laguan** [comment]
@Eghinner is this still blocked?
