### ISSUE TITLE
Change color icon

### ISSUE THREAD

**Issue by angelik0828** [Azordev/did-admin-panel#285]
**Explanation**

when entering the event view in edit event, there is a wizard button that should have the white icon

![image](https://user-images.githubusercontent.com/4030477/191783483-12fd1c7f-6295-4613-8dc2-c114b31f26ee.png)

check list 

- [ ] Change icon color to white

**Comment by Eghinner** [comment]
there are two options, fix it to take the color props or use a new svg.
https://www.svgrepo.com/
