### ISSUE TITLE
“QR redirija a una vista de datos del usuario”, (esto con el fin de verificar al ingreso del evento que sea asistente).

### ISSUE THREAD

**Issue by Eghinner** [Azordev/did-admin-panel#302]
**Explicación**

Al asistir a eventos se desea verificar que los asistentes sean socios o personas registradas previamente en DID, se desea al escanear obtener los datos de el socio y saber si su membrecía esta activa, estos datos pueden ser solicitados por personas que no son socios de DID.

**- Resultado actual:**

El QR redirige al panel administrativo sin ningún dato especifico

**- Resultado esperado:**

Redirigir al una vista en el panel administrativo que muestre los datos del socio.

**Usar como referencia esta imagen**

![Group 6](https://user-images.githubusercontent.com/4030477/197290567-d3b0d8bf-4587-4c15-bb6b-b1879e9c399f.png)

**Flujo esperado**

1. cuando el usuario este en la aplicación este ingresara a su perfil allí esta disponible el código QR
2. Al escanear Redirecciona al navegador (Se debe tener presente que el que escanea puede no ser usuario o socio de DID, este tendrá acceso a los datos del socio por el QR).
3. Podrá ver la imagen de socio y sus datos.

**Comment by Eghinner** [comment]
I suggest EE-5 for creating the view and query
@victor-heliomar
@Israel-Laguan
@Luisparr14
@joset98
Can you help us with a suggestion?

**Comment by Israel-Laguan** [comment]
I suggest EE-3, it's easier that you think only "redirect"

**Comment by Luisparr14** [comment]
I suggest EE-3 too.

**Comment by heliomar-pena** [comment]
I think in this task so:

|Task|E.E|
|-|-|
|Fix the link at the APK to the correct link (currently the APK redirects to admin.tk/{code}, I think that route will change in admin panel)|E.E 1|
|Create a new open route in admin panel to show the user information (for example: admin.tk/member)|E.E 1|
|Create the design for this new view|E.E 1 or 2|
|Create the query to show the user|E.E 1|

For me, this task is between E.E 4 and E.E 5

**Comment by e-azocar** [comment]
Is this only admin panel?

**Comment by Eghinner** [comment]
Yeah, receives in the path `admin.tk/memberCode`, does the query, and displays the view
