### ISSUE TITLE
Vista de eventos

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-admin-panel#37]
**Explanation:**

The events view must be accessed from the side menu **Events section**. This is made up of a button to create a new event which will open the corresponding view, a list of published events which contain an image, date and the name of the event.

**User Stories to Fulfill:*

- [ ] As an administrator, I would like to create a new event.
- [ ] As an administrator, I would like to see the events already published.
- [ ] As an administrator, I would like to be able to reset my password.
- [ ] As an administrator, I would like to see the date of the published events.
- [ ] As an administrator, I would like to see the name of the published events.

### Dependencies:
- [ ] The create new event button should open the corresponding view.
### References:
It has no references.

### Screenshot:
![02](https://user-images.githubusercontent.com/98891182/175752922-09df2b97-ef34-4319-836b-c38e3809075e.png)

### Workflow:
Login- Pmain- Side menu- Events

---

# SpanishVersion:

**Explicación:**

A la vista de eventos, se deberá acceder desde el menú lateral **Sección eventos**. Esta,  está compuesta por un botón para crear nuevo evento el cual le abrirá la vista correspondiente, una lista de los eventos publicados los cuales contienen una imagen, fecha y el nombre del evento.

**Historias de Usuario a Cumplir:*

- [ ]  Como administrador, quisiera crear un evento nuevo.
- [ ] Como administrador, quisiera ver los eventos ya publicados.
- [ ] Como administrador, me gustaría poder reestablecer mi contraseña.
- [ ] Como administrador, quisiera ver la fecha de los eventos publicados.
- [ ] Como administrador, quisiera ver el nombre de los eventos publicados.

### Dependencias:
- [ ] El botón de crear nuevo evento deberá abrir la vista correspondiente.
### Referencias:
No posee referencias.

### Captura de pantalla:
![02](https://user-images.githubusercontent.com/98891182/175752922-09df2b97-ef34-4319-836b-c38e3809075e.png)

### Flujo de trabajo:
Login- Pprincipal- Menú lateral- Eventos

**Comment by Eghinner** [comment]
Change layout
