### ISSUE TITLE
MEJORAR LA OPCIÓN DEL BOTÓN CREAR EVENTOS / IMPROVE THE CREATE EVENTS BUTTON OPTION

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#65]
# Explanation

Se puede ver que en la vista de  eventos,  hay una opción que  dice  crear nuevo evento y encontramos que al tocar el botón con el cursor no muestra ninguna reacción el botón debería subrayar 

You can see that in the event view, there is an option that says create new event and we found that touching the button with the cursor does not show any reaction the button should underline or 

## Screenshot

Current appearance:

![Image](https://user-images.githubusercontent.com/111365000/185748384-bdf91044-6ff0-4463-ad3b-c1ced071e7ec.png)

## Historias de usuario

Yo como usuario quiero que  al tocar con el cursor  al botón crear eventos el  tenga una reacción.

I as a user want that when I touch with the cursor on the create event button he will have a reaction.

## Criterios de aceptación.

el botón  crear eventos  reaccionara al  tener contacto con  el cursor.

the create event button will react to contact with the cursor.

## Casos de uso

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

**Comment by Israel-Laguan** [comment]
Confirmed it's working as intended
