### ISSUE TITLE
SE MOSTRARAN LOS PRODUCTOS E INFORMACION

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#66]
### Explanation

Se mostrara una cuadricula cada uno debe llevar información sobre el producto disponibles mostraran imágenes y referencias ejemplo:

![Image](https://user-images.githubusercontent.com/111365000/185968722-26628ee0-a44e-41e0-8661-555263ad0c9d.png)

Historias de usuario:

Yo como usuario quiero que en esta vista se  muestren los productos disponible con imágenes referente a cada articulo para ver las opciones.

Criterios de aceptación.

se mostraran imágenes de cada producto en cada proveedor

**Comment by Eghinner** [comment]
change design
