### ISSUE TITLE
CAMBIAR LA REACCIÓN DEL COLOR DEL TEXTO / CHANGE THE COLOR REACTION OF THE TEXT.

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#67]
##Explanation.
En la lista de eventos encontramos los títulos,  al pasar el cursor  por ellos cambia de color negro a color azul, debería tener una reacción diferente que no sea  el color del texto  ejemplo . solo el titulo del evento me parece correcto un subrayado

In the list of events we find the titles, when passing the cursor over them it changes from black to blue color, it should have a different reaction other than the color of the text example . only the title of the event seems to me correct an underline

###Checklist

En este link  puede entrar y ver.

https://www.did-admin.tk/eventos

Historia de usuario /User istory

Como usuario quiero que la lista de eventos al pasar el cursor tenga una reacción diferente que no sea el cambio de color del  texto.

As a user I want the event list to have a different reaction when hovering the cursor other than changing the color of the text.

criterios de aceptación.

 lao textos de los eventos tendrán una reacción diferente al de cambiar de color

 event texts will have a different reaction when changing color.

Casos de uso.

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

**Comment by Eghinner** [comment]
This solve effect hover for event card
![chrome_z5FSFl1mbA](https://user-images.githubusercontent.com/71513679/188242077-b103cf1c-c895-4089-b295-8b2c50313059.png)
