### ISSUE TITLE
HACER UNA VISTA PARA NUEVO PROVEEDOR ./  MAKE A VIEW FOR A NEW SUPPLIER .

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#90]
### EXPLANATION

Al seleccionar nuevo proveedor se pasara a la siguiente vista donde se abrirá un espacio para pedir una serie de datos para ingresar a proveedor  el primer dato que pedirá sera el nombre de la empresa con el titulo "Nombre de la empresa " y debajo estará un espacio para poder escribir el nombre de la empresa a ingresar

When you select new supplier you will go to the next view where a space will open to ask for a series of data to enter the supplier, the first data requested will be the name of the company with the title "Name of the company" and below will be a space to write the name of the company to enter.

### SCREENSHOTS

![Image](https://user-images.githubusercontent.com/111365000/187215789-75f3440a-90d8-44ce-bee5-682d18734b8f.png)

 Crear este titulo y espacio

![Image](https://user-images.githubusercontent.com/111365000/186680353-6f9b96b8-9625-45c3-be75-72b89aa0339c.png)

### USER STORY

Yo como usuario proveedor quiero que al seleccionar "Añadir nuevo proveedor" se muestre una vista  donde  se muestre la opción de " nombre de la empresa" para que pueda  afiliar mi empresa 

As a supplier user, I want to select "Add new supplier" to display a view where the "company name" option is shown so that I can affiliate my company. 

### ACEPTANCE CRITERIA

En esta vista se dará un espacio con el titulo "nombre de la empresa" para agregarla y pueda afiliarme

In this view there will be a space with the title "name of the company" to add it so that I can become a member.

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

**Comment by Eghinner** [comment]
@yanfranve any progress?

**Comment by JRS-Developer** [comment]
@Eghinner @Israel-Laguan 
Hello, I noticed that when I click the Regresar button in returns to the index page. localhost:3000/

It should return to the list of providers no? Because it always return me to the index page.

https://user-images.githubusercontent.com/77207702/188924080-a02ea9bc-3f08-4ec5-a499-32de602155f1.mov




I think it's because of this property: Should I change it or that's the expected behaviour?
![image](https://user-images.githubusercontent.com/77207702/188922758-f9b9fd1b-9d8e-4fec-b48b-a5a751996511.png)

**Comment by JRS-Developer** [comment]
And in the design it asks for "Fecha de Inicio" and "Password", but in types there are no any property that match any of them in the interface ProviderEditable.

![image](https://user-images.githubusercontent.com/77207702/188930077-6a64df2c-84de-4765-a337-3c9ddf02826d.png)

**Comment by Israel-Laguan** [comment]
> @Eghinner @Israel-Laguan Hello, I noticed that when I click the Regresar button in returns to the index page. localhost:3000/
> 
> It should return to the list of providers no? Because it always return me to the index page.

I think its the redirect function, not the one you mention, currently it just back, it can have more logic

@Eghinner please help

**Comment by JRS-Developer** [comment]
> > @Eghinner @Israel-Laguan Hello, I noticed that when I click the Regresar button in returns to the index page. localhost:3000/
> > It should return to the list of providers no? Because it always return me to the index page.
> 
> I think its the redirect function, not the one you mention
> 
> @Eghinner please help

Yes, it was the replace property,I removed it and now it works as it should.

**Comment by Eghinner** [comment]
thanks

**Comment by JRS-Developer** [comment]
> And in the design it asks for "Fecha de Inicio" and "Password", but in types there are no any property that match any of them in the interface ProviderEditable.
> 
> ![image](https://user-images.githubusercontent.com/77207702/188930077-6a64df2c-84de-4765-a337-3c9ddf02826d.png)

Someone can help me with this? Because I don't know if the backend can return password and fecha de inicio

**Comment by Eghinner** [comment]
> And in the design it asks for "Fecha de Inicio" and "Password", but in types there are no any property that match any of them in the interface ProviderEditable.
> 
> ![image](https://user-images.githubusercontent.com/77207702/188930077-6a64df2c-84de-4765-a337-3c9ddf02826d.png)

Ok, I think we have to wait while that endpoint is being developed.

**Comment by Eghinner** [comment]
https://github.com/Azordev/did-admin-panel/pull/190 @JRS-Developer  you can now continue

**Comment by JRS-Developer** [comment]
> https://github.com/Azordev/did-admin-panel/pull/190 @JRS-Developer  you can now continue

Ok, I'll continue with this task this afternoon.

**Comment by JRS-Developer** [comment]
@Israel-Laguan @Eghinner 
Hello, I noticed than in layout.scss file there is a mixin than I think it creates some spacing utils, but I don't know if this is the wanted result.

![image](https://user-images.githubusercontent.com/77207702/189409329-bfbdd5cd-3857-4007-9098-872a393ff8c6.png)

**Comment by JRS-Developer** [comment]
And what is memberCode? is it the userName? because in the design there is a "Usuario" field and I don't know which property should I use.
https://github.com/Azordev/did-admin-panel/pull/190/files#diff-5ef36bdba3fea5931f14022d8831cb7d82e93b75b64f88f560ce0e35952efc2eR76

**Comment by JRS-Developer** [comment]
And there are two email fields. Which one should I use? b2bEmail or salesEmail?
https://github.com/Azordev/did-admin-panel/pull/190/files#diff-29ef4cf56e8f7a025b575c4758db43447cafc42aef6a93fe056cee91936c8e31R57

**Comment by JRS-Developer** [comment]
@Eghinner @Israel-Laguan @e-azocar 
Hello, I noticed another problem. I can't create a provider without an email. At the first try I could create a provider but with an empty email but I had to modify the file controllers/providers (I modified it because I couldn't create a provider because it wasn't accepting Null values). 

![image](https://user-images.githubusercontent.com/77207702/189459853-b888f6a7-cf25-44ad-a365-28b30b3fc67e.png)


Now it shows this error.
![image](https://user-images.githubusercontent.com/77207702/189459681-cb10341b-9ef0-4891-ac82-84f99c87e4d6.png)

And it shows that error because I created a providerUser with an empty email and now I can't create more providers because this param has to be unique. Any recommendations?

Maybe it's needed to make changes in the design or in the API.

**Comment by e-azocar** [comment]
> @Eghinner @Israel-Laguan @e-azocar Hello, I noticed another problem. I can't create a provider without an email. At the first try I could create a provider but with an empty email but I had to modify the file controllers/providers (I modified it because I couldn't create a provider because it wasn't accepting Null values).
> 
> ![image](https://user-images.githubusercontent.com/77207702/189459853-b888f6a7-cf25-44ad-a365-28b30b3fc67e.png)
> 
> Now it shows this error. ![image](https://user-images.githubusercontent.com/77207702/189459681-cb10341b-9ef0-4891-ac82-84f99c87e4d6.png)
> 
> And it shows that error because I created a providerUser with an empty email and now I can't create more providers because this param has to be unique. Any recommendations?
> 
> Maybe it's needed to make changes in the design or in the API.

@JRS-Developer please avoid change API or Controller files, only don't send null values, the message in console means you can't create a new provider with a duplicated emails, I mean, an existing email in DB

**Comment by JRS-Developer** [comment]
> > @Eghinner @Israel-Laguan @e-azocar Hello, I noticed another problem. I can't create a provider without an email. At the first try I could create a provider but with an empty email but I had to modify the file controllers/providers (I modified it because I couldn't create a provider because it wasn't accepting Null values).
> > ![image](https://user-images.githubusercontent.com/77207702/189459853-b888f6a7-cf25-44ad-a365-28b30b3fc67e.png)
> > Now it shows this error. ![image](https://user-images.githubusercontent.com/77207702/189459681-cb10341b-9ef0-4891-ac82-84f99c87e4d6.png)
> > And it shows that error because I created a providerUser with an empty email and now I can't create more providers because this param has to be unique. Any recommendations?
> > Maybe it's needed to make changes in the design or in the API.
> 
> @JRS-Developer please avoid change API or Controller files, only don't send null values, the message in console means you can't create a new provider with a duplicated emails, I mean, an existing email in DB

Ok, I will restore those changes. But I still can't create new providers because the endpoint doesn't accept null values.
