### ISSUE TITLE
TAMBIEN ESTARA EL BOTON "REGRESAR"./ THERE WILL ALSO BE A "BACK" BUTTON

### ISSUE THREAD

**Issue by elias-miguel-vergara** [Azordev/did-admin-panel#96]
###EXPLANATION. 
de pues de haber seleccionado añadir nuevo proveedor se mostrara una vista de pantalla donde  se muestra unos espacios donde pide unos datos  y en la parte superior de la pantalla estará el botón regresar que te lleva al vista anterior donde estaban  la lista de productos disponible del proveedor

.
after selecting add new supplier, a screen view will be displayed showing some spaces where it asks for some data and at the top of the screen there will be a back button that takes you to the previous view where the list of available products of the supplier was.

###SCREENSHOTS.
1 Vista donde se encuentra el boton regresar.

![Image](https://user-images.githubusercontent.com/111365000/187220165-976f17ee-7c65-4ca4-9ab2-261265481a1c.png)

  
 2 Boton regresar que se va a crear

![Image](https://user-images.githubusercontent.com/111365000/187220252-f207b0d3-cd79-46e2-b94c-bc395be805e3.png)

3 Al darle la opcion regresar se regresa a  esta vista

![Image](https://user-images.githubusercontent.com/111365000/187220345-d940fa5c-5ff5-464f-8804-d188a9bca6d5.png)

### CHECKLIST.

Esta opción estará disponible para  el usuario cuando decida regresar una vista  este botón estará disponible en cualquier momento

This option will be available to the user when he/she decides to return to a view, this button will be available at any time.

###RELATED ISSUES.

https://github.com/orgs/Azordev/projects/14/views/1

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

**Comment by Eghinner** [comment]
@PrototypeK02 any progress?

**Comment by PrototypeK02** [comment]
it was done more than a week ago @Eghinner

**Comment by Eghinner** [comment]
jeje, ok. hmmm, do you remember #PR?
